// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMd1FERwXLL5CDa0BUd_YzL0cG027nIhM',
    appId: '1:576949631415:web:ee997c5d473ca981c15032',
    messagingSenderId: '576949631415',
    projectId: 'shoesapp-2e87b',
    authDomain: 'shoesapp-2e87b.firebaseapp.com',
    databaseURL: 'https://shoesapp-2e87b-default-rtdb.firebaseio.com',
    storageBucket: 'shoesapp-2e87b.appspot.com',
    measurementId: 'G-87R53JW0VS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-De1xMIIVyjN9Qp3VHDWPDgquxabex64',
    appId: '1:576949631415:android:db060e7bb250d56ec15032',
    messagingSenderId: '576949631415',
    projectId: 'shoesapp-2e87b',
    databaseURL: 'https://shoesapp-2e87b-default-rtdb.firebaseio.com',
    storageBucket: 'shoesapp-2e87b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxpg20aK4Yp79kUmvBlvzq8N5Z3AO0mEI',
    appId: '1:576949631415:ios:8ac080707856246ec15032',
    messagingSenderId: '576949631415',
    projectId: 'shoesapp-2e87b',
    databaseURL: 'https://shoesapp-2e87b-default-rtdb.firebaseio.com',
    storageBucket: 'shoesapp-2e87b.appspot.com',
    iosBundleId: 'com.example.myshoesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxpg20aK4Yp79kUmvBlvzq8N5Z3AO0mEI',
    appId: '1:576949631415:ios:efff7f095975d2e7c15032',
    messagingSenderId: '576949631415',
    projectId: 'shoesapp-2e87b',
    databaseURL: 'https://shoesapp-2e87b-default-rtdb.firebaseio.com',
    storageBucket: 'shoesapp-2e87b.appspot.com',
    iosBundleId: 'com.example.myshoesapp.RunnerTests',
  );
}
